### ISSUE TITLE
setup.py develop mosquitto fails

### ISSUE THREAD

**Issue by einsiedlerkrebs** [hiveeyes/beradio#1]
installation drops this error

```
Searching for mosquitto==1.2.3
Reading https://pypi.python.org/simple/mosquitto/
Couldn't find index page for 'mosquitto' (maybe misspelled?)
```

package [seems](https://pypi.python.org/pypi?%3Aaction=search&term=mosquitto&submit=search) to be disapeared.

Therefore, distibutional install of mosquitto does not solve the issue.

gr eins

**Comment by amotl** [comment]
Sorry for that, we should have moved on to the fine MQTT library from Eclipse Paho, "[paho-mqtt](https://pypi.python.org/pypi/paho-mqtt)".
Will let you know about any updates on that, thanks for testing!

**Comment by amotl** [comment]
You might want to try this in the meanwhile:
`easy_install https://packages.hiveeyes.org/hiveeyes/python/eggs/mosquitto/mosquitto-1.2.3-py2.7.egg`

**Comment by amotl** [comment]
Now using [paho-mqtt](https://pypi.python.org/pypi/paho-mqtt) per d187c1653b. Thanks again for reporting!

**Comment by einsiedlerkrebs** [comment]
thanks, that fixed worked for me
